-- AlterTable
ALTER TABLE "User" ADD COLUMN     "generationsLimit" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "generationsUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastResetDate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
